package com.se.sample.objects;

import java.util.*;
import java.util.stream.Collectors;
public class GroupByMapMultipleFields {
    // Define a simple class for the composite key, ensuring proper equals/hashCode
    public static class GroupKey {
        private final Object field1;
        private final Object field2;

        public GroupKey(Object field1, Object field2) {
            this.field1 = field1;
            this.field2 = field2;
        }

        // Ensure equals() and hashCode() are implemented (can be auto-generated by IDE or a record)
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            GroupKey groupKey = (GroupKey) o;
            return Objects.equals(field1, groupKey.field1) && Objects.equals(field2, groupKey.field2);
        }

        @Override
        public int hashCode() {
            return Objects.hash(field1, field2);
        }

        @Override
        public String toString() {
            return "Key{" + field1 + ", " + field2 + '}';
        }
    }

    public static void main(String[] args) {
        List<Map<String, Object>> data = new ArrayList<>();
        // Sample data
        data.add(Map.of("id", 1, "name", "A", "type", "X"));
        data.add(Map.of("id", 1, "name", "B", "type", "Y"));
        data.add(Map.of("id", 2, "name", "A", "type", "Z"));
        data.add(Map.of("id", 1, "name", "A", "type", "W"));

        // Group by "id" and "name" using the composite key
        Map<GroupKey, List<Map<String, Object>>> groupedByMultipleFields = data.stream()
                .collect(Collectors.groupingBy(
                        map -> new GroupKey(map.get("id"), map.get("name"))
                ));

        System.out.println(groupedByMultipleFields);
    }
}
